server:
	javac ConfigFileParser.java
	javac LogWriter.java
	javac OpenFiles.java
	javac server.java
client:
	javac ConfigFileParser.java
	javac LogWriter.java
	javac OpenFiles.java
	javac client.java
clean:
	rm *.class
